services:

  # Just create device for simulate real Serial-port 
  # with random output and 9600 b/s speed
  sim_dev:
    build: .
    command: sim_dev
    privileged: true
    environment:
      - DEVICE_COUNT=3
      - DEFAULT_SPEED=9600
      - TIME_DILATION=600 # for debug
    volumes:
      - /dev:/dev:rw
  
  emu_record:
    build: .
    command: emu_record
    privileged: true
    environment:
      - EMU_CONFIG_PATH=/etc/example_config.yaml
    depends_on:
      - sim_dev
    volumes:
      - ./example_config.yaml:/etc/example_config.yaml # config path  
      - /dev:/dev:rw