version: 1.0.0
devices: 
  - input: /dev/ttyUSB0
    output: /dev/ttyUSB0_VIRT
    speed: 9600
    size: 8
  - input: /dev/ttyUSB1
    output: /dev/ttyUSB1_VIRT
    speed: 9600
    size: 8
  - input: /dev/ttyUSB2
    output: /dev/ttyUSB2_VIRT
    speed: 9600
    size: 8