FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        v4l-utils \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["ffmpeg"]
