FROM golang:1.18

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod .
COPY main.go .

RUN go build -o camera-recorder .

ENTRYPOINT ["./camera-recorder"]
